/* SPDX-License-Identifier: GPL-2.0 */
#ifndef SELF_TEST_PAGE_H_
#define SELF_TEST_PAGE_H_

static const char self_test_page[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Bitaxe Self Test</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{background:#111;color:#e0e0e0;font-family:'Courier New',monospace;"
"padding:16px;font-size:14px}"
"h1{color:#00ff41;font-size:20px;margin-bottom:12px}"
"h2{color:#ccc;font-size:15px;margin:16px 0 8px;border-bottom:1px solid #333;"
"padding-bottom:4px}"
".bar{background:#222;border:1px solid #333;padding:10px 14px;"
"margin-bottom:12px;border-radius:4px}"
".bar .lbl{color:#888;font-size:11px;text-transform:uppercase}"
".bar .val{color:#00ff41;font-size:16px;margin-top:2px}"
".bar.fail .val{color:#ff4444}"
".bar.pass .val{color:#00ff41}"
"button{background:#333;color:#e0e0e0;border:1px solid #555;"
"padding:8px 18px;margin:4px;cursor:pointer;font-family:inherit;"
"font-size:13px;border-radius:3px}"
"button:hover{background:#444}"
"button:disabled{opacity:0.4;cursor:not-allowed}"
"button.start{border-color:#00ff41;color:#00ff41}"
"button.rst{border-color:#ff4444;color:#ff4444}"
"button.save{border-color:#4488ff;color:#4488ff}"
"table{width:100%;border-collapse:collapse;margin-top:12px}"
"th,td{text-align:left;padding:6px 10px;border-bottom:1px solid #333}"
"th{color:#888;font-size:11px;text-transform:uppercase}"
"td{font-size:13px}"
".pass-c{color:#00ff41}.fail-c{color:#ff4444}.run-c{color:#ffaa00}"
"#log{background:#0a0a0a;border:1px solid #333;padding:8px;"
"margin-top:12px;max-height:150px;overflow-y:auto;font-size:12px;"
"white-space:pre-wrap;border-radius:4px}"
".metrics{display:flex;gap:8px;flex-wrap:wrap}"
".metrics .bar{flex:1;min-width:100px}"
".cfg{background:#1a1a1a;border:1px solid #333;padding:12px;"
"border-radius:4px;margin-bottom:12px}"
".cfg label{display:block;color:#888;font-size:11px;"
"text-transform:uppercase;margin-top:8px}"
".cfg label:first-child{margin-top:0}"
".cfg input{width:100%;background:#222;border:1px solid #444;"
"color:#e0e0e0;padding:6px 8px;font-family:inherit;font-size:13px;"
"border-radius:3px;margin-top:2px}"
".cfg input:focus{outline:none;border-color:#4488ff}"
".cfg-row{display:flex;gap:8px}"
".cfg-row>div{flex:1}"
".cfg-row>.small{max-width:120px}"
".cfg-msg{font-size:12px;margin-top:6px;min-height:16px}"
"</style></head><body>"
"<h1>Bitaxe Self Test</h1>"

"<div class='bar' id='status-bar'>"
"<div class='lbl'>Status</div>"
"<div class='val' id='status'>Connecting...</div></div>"

"<div class='metrics'>"
"<div class='bar'><div class='lbl'>Hashrate</div>"
"<div class='val' id='hr'>--</div></div>"
"<div class='bar'><div class='lbl'>Temperature</div>"
"<div class='val' id='temp'>--</div></div>"
"<div class='bar'><div class='lbl'>Core Voltage</div>"
"<div class='val' id='vcore'>--</div></div></div>"

"<div style='margin:12px 0'>"
"<button class='start' id='btn-start' onclick='startTest()'>Start Test</button>"
"<button class='rst' onclick='restartDev()'>Restart Device</button></div>"

"<table><thead><tr><th>Test</th><th>Status</th>"
"<th>Detail</th></tr></thead>"
"<tbody id='results'></tbody></table>"

"<h2>Connection Config</h2>"
"<div class='cfg'>"
"<label>WiFi SSID<input id='c-ssid' type='text'></label>"
"<label>WiFi Password<input id='c-pass' type='password'></label>"
"<label>Hostname<input id='c-host' type='text'></label>"
"<div class='cfg-row'>"
"<div><label>Stratum URL<input id='c-surl' type='text'></label></div>"
"<div class='small'><label>Port<input id='c-sport' type='number'></label></div></div>"
"<label>Stratum User<input id='c-suser' type='text'></label>"
"<label>Stratum Password<input id='c-spass' type='password'></label>"
"<div style='margin-top:10px'>"
"<button class='save' onclick='saveConfig()'>Save Config</button>"
"<button onclick='loadConfig()'>Reload</button></div>"
"<div class='cfg-msg' id='cfg-msg'></div>"
"</div>"

"<div id='log'></div>"

"<script>"
"var ws,results={};"
"function conn(){"
"var h=location.host;"
"ws=new WebSocket('ws://'+h+'/ws');"
"ws.onopen=function(){setStatus('Connected','');loadConfig();};"
"ws.onclose=function(){setStatus('Disconnected','fail');"
"setTimeout(conn,2000);};"
"ws.onmessage=function(e){"
"try{var m=JSON.parse(e.data);handle(m);}catch(x){addLog(e.data);}"
"};}"
"function handle(m){"
"if(m.type==='status'){"
"results[m.test]={state:m.state,detail:m.detail};"
"setStatus('Testing: '+m.test,'');"
"render();"
"}else if(m.type==='result'){"
"results[m.test]={state:m.state,detail:m.detail};"
"render();"
"}else if(m.type==='metrics'){"
"if(m.hashrate!==undefined)"
"document.getElementById('hr').textContent=m.hashrate.toFixed(1)+' GH/s';"
"if(m.temperature!==undefined)"
"document.getElementById('temp').textContent=m.temperature.toFixed(1)+' C';"
"if(m.core_voltage!==undefined)"
"document.getElementById('vcore').textContent=m.core_voltage+' mV';"
"}else if(m.type==='done'){"
"var b=document.getElementById('status-bar');"
"if(m.passed){setStatus('ALL TESTS PASSED','pass');b.className='bar pass';}"
"else{setStatus('TESTS FAILED','fail');b.className='bar fail';}"
"document.getElementById('btn-start').disabled=false;"
"}else if(m.type==='log'){"
"addLog(m.msg);"
"}}"
"function setStatus(t,c){"
"var el=document.getElementById('status');el.textContent=t;"
"el.className='val'+(c?' '+c+'-c':'');}"
"function render(){"
"var tb=document.getElementById('results');tb.innerHTML='';"
"for(var k in results){"
"var r=results[k],tr=document.createElement('tr');"
"var sc=r.state==='pass'?'pass-c':(r.state==='fail'?'fail-c':'run-c');"
"tr.innerHTML='<td>'+k+'</td><td class=\"'+sc+'\">'"
"+r.state.toUpperCase()+'</td><td>'+r.detail+'</td>';"
"tb.appendChild(tr);}}"
"function addLog(t){"
"var el=document.getElementById('log');"
"el.textContent+=t+'\\n';el.scrollTop=el.scrollHeight;}"
"function startTest(){"
"var x=new XMLHttpRequest();"
"x.open('POST','/api/test/start');"
"x.onload=function(){"
"if(x.status===200){results={};render();"
"document.getElementById('btn-start').disabled=true;"
"document.getElementById('hr').textContent='--';"
"document.getElementById('temp').textContent='--';"
"document.getElementById('vcore').textContent='--';"
"setStatus('Starting...','');"
"document.getElementById('status-bar').className='bar';"
"}else if(x.status===409){setStatus('Test already running','');}"
"else{setStatus('Error: '+x.statusText,'fail');}};"
"x.send();}"
"function restartDev(){"
"if(!confirm('Restart the device?'))return;"
"var x=new XMLHttpRequest();"
"x.open('POST','/api/system/restart');"
"x.onload=function(){setStatus('Restarting...','');};"
"x.send();}"
"function loadConfig(){"
"var x=new XMLHttpRequest();"
"x.open('GET','/api/config');"
"x.onload=function(){"
"if(x.status===200){"
"var c=JSON.parse(x.responseText);"
"document.getElementById('c-ssid').value=c.wifi_ssid||'';"
"document.getElementById('c-pass').value='';"
"document.getElementById('c-host').value=c.hostname||'';"
"document.getElementById('c-surl').value=c.stratum_url||'';"
"document.getElementById('c-sport').value=c.stratum_port||'';"
"document.getElementById('c-suser').value=c.stratum_user||'';"
"document.getElementById('c-spass').value='';"
"cfgMsg('Loaded','#888');"
"}};"
"x.send();}"
"function saveConfig(){"
"var body={};"
"var v;"
"v=document.getElementById('c-ssid').value;if(v)body.wifi_ssid=v;"
"v=document.getElementById('c-pass').value;if(v)body.wifi_pass=v;"
"v=document.getElementById('c-host').value;if(v)body.hostname=v;"
"v=document.getElementById('c-surl').value;if(v)body.stratum_url=v;"
"v=document.getElementById('c-sport').value;if(v)body.stratum_port=parseInt(v);"
"v=document.getElementById('c-suser').value;if(v)body.stratum_user=v;"
"v=document.getElementById('c-spass').value;if(v)body.stratum_pass=v;"
"var x=new XMLHttpRequest();"
"x.open('POST','/api/config');"
"x.setRequestHeader('Content-Type','application/json');"
"x.onload=function(){"
"if(x.status===200){cfgMsg('Saved! Restart to apply.','#00ff41');}"
"else{cfgMsg('Error saving: '+x.statusText,'#ff4444');}};"
"x.send(JSON.stringify(body));}"
"function cfgMsg(t,c){"
"var el=document.getElementById('cfg-msg');"
"el.textContent=t;el.style.color=c;}"
"conn();"
"</script></body></html>";

#endif /* SELF_TEST_PAGE_H_ */
