name: build-target
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build web dist
      working-directory: ./main/http_server/axe-os
      run: |
        npm ci
        npm run build
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32s2
        path: '.'
    - name: upload esp-miner.bin
      uses: actions/upload-artifact@v3
      with:
        name: esp-miner.bin
        path: ./build/esp-miner.bin
    - name: upload www.bin
      uses: actions/upload-artifact@v3
      with:
        name: www.bin
        path: ./build/www.bin
